# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b12369e04696897d36a368b58047f0e2877179a290fc2023e40266ffbcd89df8359e2b42a1a8b8594aade1a18c21b0f74726545bed1459693fd668625d75280b

test:
  secret_key_base: 29de7c1c30281bceddb961db69ae9ea473b5f55bd3d494583908fa6787c97076110086fb52fac95097a8582eec9339e89536c598b4caf0e3183c85bef366ba9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
